### ISSUE TITLE
unrestricted input cause bug

### ISSUE THREAD

**Issue by MrKira128** [MinaRomany53/Auto-Text-effect#1]
https://user-images.githubusercontent.com/50806393/153783055-b95344ec-b93f-48b3-806f-8c24dae36da8.mp4

**Comment by MinaRomany53** [comment]
done

‫في الاثنين، 14 فبراير 2022 في 2:48 ص تمت كتابة ما يلي بواسطة ‪Ahmed Kira‬‏
***@***.***‬‏>:‬

**Comment by MinaRomany53** [comment]
https://minaromany53.github.io/Auto-Text-effect/

**Comment by MrKira128** [comment]
nice, it's great btw.

**Comment by MinaRomany53** [comment]
Awesome, thanks!

‫في الثلاثاء، 15 فبراير 2022 في 12:48 ص تمت كتابة ما يلي بواسطة ‪Ahmed
Kira‬‏ ***@***.***‬‏>:‬
